# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.2.0.schema.json

PackageIdentifier: WorkdayInc.OfficeConnect
PackageVersion: 2022.105.2718.2929
PackageLocale: en-US
Publisher: Workday, Inc.
PackageName: OfficeConnect
License: Proprietary
Copyright: Copyright (c) Workday, Inc.. All rights reserved.
ShortDescription: OfficeConnect makes it easy to create reports in Microsoft Office. Connect your existing Excel reports to Workday Adaptive Planning, or create new presentation-quality reports from a blank slate.
ManifestType: defaultLocale
ManifestVersion: 1.2.0

